//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carcel.Visita {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service/", ConfigurationName="Visita.WSVisita")]
    public interface WSVisita {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVisita/removeRequest", ReplyAction="http://service/WSVisita/removeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarVisitaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarVisita))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscar))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.Visita.removeResponse1 remove(Carcel.Visita.removeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVisita/removeRequest", ReplyAction="http://service/WSVisita/removeResponse")]
        System.Threading.Tasks.Task<Carcel.Visita.removeResponse1> removeAsync(Carcel.Visita.removeRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVisita/countRequest", ReplyAction="http://service/WSVisita/countResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarVisitaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarVisita))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscar))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.Visita.countResponse1 count(Carcel.Visita.countRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVisita/countRequest", ReplyAction="http://service/WSVisita/countResponse")]
        System.Threading.Tasks.Task<Carcel.Visita.countResponse1> countAsync(Carcel.Visita.countRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVisita/findRequest", ReplyAction="http://service/WSVisita/findResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarVisitaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarVisita))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscar))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.Visita.findResponse1 find(Carcel.Visita.findRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVisita/findRequest", ReplyAction="http://service/WSVisita/findResponse")]
        System.Threading.Tasks.Task<Carcel.Visita.findResponse1> findAsync(Carcel.Visita.findRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVisita/createRequest", ReplyAction="http://service/WSVisita/createResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarVisitaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarVisita))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscar))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.Visita.createResponse1 create(Carcel.Visita.createRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVisita/createRequest", ReplyAction="http://service/WSVisita/createResponse")]
        System.Threading.Tasks.Task<Carcel.Visita.createResponse1> createAsync(Carcel.Visita.createRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVisita/agregarVisitaRequest", ReplyAction="http://service/WSVisita/agregarVisitaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarVisitaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarVisita))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscar))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.Visita.agregarVisitaResponse1 agregarVisita(Carcel.Visita.agregarVisitaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVisita/agregarVisitaRequest", ReplyAction="http://service/WSVisita/agregarVisitaResponse")]
        System.Threading.Tasks.Task<Carcel.Visita.agregarVisitaResponse1> agregarVisitaAsync(Carcel.Visita.agregarVisitaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVisita/findAllRequest", ReplyAction="http://service/WSVisita/findAllResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarVisitaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarVisita))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscar))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.Visita.findAllResponse findAll(Carcel.Visita.findAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVisita/findAllRequest", ReplyAction="http://service/WSVisita/findAllResponse")]
        System.Threading.Tasks.Task<Carcel.Visita.findAllResponse> findAllAsync(Carcel.Visita.findAllRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVisita/findRangeRequest", ReplyAction="http://service/WSVisita/findRangeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarVisitaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarVisita))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscar))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.Visita.findRangeResponse findRange(Carcel.Visita.findRangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVisita/findRangeRequest", ReplyAction="http://service/WSVisita/findRangeResponse")]
        System.Threading.Tasks.Task<Carcel.Visita.findRangeResponse> findRangeAsync(Carcel.Visita.findRangeRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVisita/editRequest", ReplyAction="http://service/WSVisita/editResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarVisitaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarVisita))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscar))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.Visita.editResponse1 edit(Carcel.Visita.editRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVisita/editRequest", ReplyAction="http://service/WSVisita/editResponse")]
        System.Threading.Tasks.Task<Carcel.Visita.editResponse1> editAsync(Carcel.Visita.editRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVisita/buscarRequest", ReplyAction="http://service/WSVisita/buscarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarVisitaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarVisita))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscar))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.Visita.buscarResponse1 buscar(Carcel.Visita.buscarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSVisita/buscarRequest", ReplyAction="http://service/WSVisita/buscarResponse")]
        System.Threading.Tasks.Task<Carcel.Visita.buscarResponse1> buscarAsync(Carcel.Visita.buscarRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class visita : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short edadField;
        
        private horario horarioIdHorarioField;
        
        private string idVisitaField;
        
        private string nombreVField;
        
        private string observacionField;
        
        private preso presoIdPresoField;
        
        private short tiempoVisitaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public short edad {
            get {
                return this.edadField;
            }
            set {
                this.edadField = value;
                this.RaisePropertyChanged("edad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public horario horarioIdHorario {
            get {
                return this.horarioIdHorarioField;
            }
            set {
                this.horarioIdHorarioField = value;
                this.RaisePropertyChanged("horarioIdHorario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string idVisita {
            get {
                return this.idVisitaField;
            }
            set {
                this.idVisitaField = value;
                this.RaisePropertyChanged("idVisita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombreV {
            get {
                return this.nombreVField;
            }
            set {
                this.nombreVField = value;
                this.RaisePropertyChanged("nombreV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string observacion {
            get {
                return this.observacionField;
            }
            set {
                this.observacionField = value;
                this.RaisePropertyChanged("observacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public preso presoIdPreso {
            get {
                return this.presoIdPresoField;
            }
            set {
                this.presoIdPresoField = value;
                this.RaisePropertyChanged("presoIdPreso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public short tiempoVisita {
            get {
                return this.tiempoVisitaField;
            }
            set {
                this.tiempoVisitaField = value;
                this.RaisePropertyChanged("tiempoVisita");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class horario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionHField;
        
        private short idHorarioField;
        
        private bool idHorarioFieldSpecified;
        
        private short minutosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionH {
            get {
                return this.descripcionHField;
            }
            set {
                this.descripcionHField = value;
                this.RaisePropertyChanged("descripcionH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public short idHorario {
            get {
                return this.idHorarioField;
            }
            set {
                this.idHorarioField = value;
                this.RaisePropertyChanged("idHorario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idHorarioSpecified {
            get {
                return this.idHorarioFieldSpecified;
            }
            set {
                this.idHorarioFieldSpecified = value;
                this.RaisePropertyChanged("idHorarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public short minutos {
            get {
                return this.minutosField;
            }
            set {
                this.minutosField = value;
                this.RaisePropertyChanged("minutos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class createResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class create : object, System.ComponentModel.INotifyPropertyChanged {
        
        private visita entityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public visita entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
                this.RaisePropertyChanged("entity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class countResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class count : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class agregarVisitaResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class agregarVisita : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string observacionField;
        
        private int idPresoField;
        
        private string nombreField;
        
        private short edadField;
        
        private int idHorarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string observacion {
            get {
                return this.observacionField;
            }
            set {
                this.observacionField = value;
                this.RaisePropertyChanged("observacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idPreso {
            get {
                return this.idPresoField;
            }
            set {
                this.idPresoField = value;
                this.RaisePropertyChanged("idPreso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public short edad {
            get {
                return this.edadField;
            }
            set {
                this.edadField = value;
                this.RaisePropertyChanged("edad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idHorario {
            get {
                return this.idHorarioField;
            }
            set {
                this.idHorarioField = value;
                this.RaisePropertyChanged("idHorario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class findAll : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class removeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class remove : object, System.ComponentModel.INotifyPropertyChanged {
        
        private visita entityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public visita entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
                this.RaisePropertyChanged("entity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class buscarResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private visita returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public visita @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class buscar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class editResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class edit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private visita entityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public visita entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
                this.RaisePropertyChanged("entity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class findResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private visita returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public visita @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class find : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class penal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private short idPenalField;
        
        private bool idPenalFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public short idPenal {
            get {
                return this.idPenalField;
            }
            set {
                this.idPenalField = value;
                this.RaisePropertyChanged("idPenal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPenalSpecified {
            get {
                return this.idPenalFieldSpecified;
            }
            set {
                this.idPenalFieldSpecified = value;
                this.RaisePropertyChanged("idPenalSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class preso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short idPresoField;
        
        private bool idPresoFieldSpecified;
        
        private string nombreVField;
        
        private penal penalIdPenalField;
        
        private ushort sexoVField;
        
        private bool sexoVFieldSpecified;
        
        private ushort visitaVField;
        
        private bool visitaVFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public short idPreso {
            get {
                return this.idPresoField;
            }
            set {
                this.idPresoField = value;
                this.RaisePropertyChanged("idPreso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPresoSpecified {
            get {
                return this.idPresoFieldSpecified;
            }
            set {
                this.idPresoFieldSpecified = value;
                this.RaisePropertyChanged("idPresoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombreV {
            get {
                return this.nombreVField;
            }
            set {
                this.nombreVField = value;
                this.RaisePropertyChanged("nombreV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public penal penalIdPenal {
            get {
                return this.penalIdPenalField;
            }
            set {
                this.penalIdPenalField = value;
                this.RaisePropertyChanged("penalIdPenal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ushort sexoV {
            get {
                return this.sexoVField;
            }
            set {
                this.sexoVField = value;
                this.RaisePropertyChanged("sexoV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sexoVSpecified {
            get {
                return this.sexoVFieldSpecified;
            }
            set {
                this.sexoVFieldSpecified = value;
                this.RaisePropertyChanged("sexoVSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public ushort visitaV {
            get {
                return this.visitaVField;
            }
            set {
                this.visitaVField = value;
                this.RaisePropertyChanged("visitaV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool visitaVSpecified {
            get {
                return this.visitaVFieldSpecified;
            }
            set {
                this.visitaVFieldSpecified = value;
                this.RaisePropertyChanged("visitaVSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="remove", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class removeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.Visita.visita entity;
        
        public removeRequest() {
        }
        
        public removeRequest(Carcel.Visita.visita entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class removeResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public removeResponse1() {
        }
        
        public removeResponse1(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="count", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class countRequest {
        
        public countRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="countResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class countResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public countResponse1() {
        }
        
        public countResponse1(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="find", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object id;
        
        public findRequest() {
        }
        
        public findRequest(object id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.Visita.visita @return;
        
        public findResponse1() {
        }
        
        public findResponse1(Carcel.Visita.visita @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="create", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class createRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.Visita.visita entity;
        
        public createRequest() {
        }
        
        public createRequest(Carcel.Visita.visita entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class createResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public createResponse1() {
        }
        
        public createResponse1(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregarVisita", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class agregarVisitaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string observacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPreso;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short edad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idHorario;
        
        public agregarVisitaRequest() {
        }
        
        public agregarVisitaRequest(string id, string observacion, int idPreso, string nombre, short edad, int idHorario) {
            this.id = id;
            this.observacion = observacion;
            this.idPreso = idPreso;
            this.nombre = nombre;
            this.edad = edad;
            this.idHorario = idHorario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregarVisitaResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class agregarVisitaResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public agregarVisitaResponse1() {
        }
        
        public agregarVisitaResponse1(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAll", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findAllRequest {
        
        public findAllRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.Visita.visita[] @return;
        
        public findAllResponse() {
        }
        
        public findAllResponse(Carcel.Visita.visita[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findRange", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findRangeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("range", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int>[] range;
        
        public findRangeRequest() {
        }
        
        public findRangeRequest(System.Nullable<int>[] range) {
            this.range = range;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findRangeResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findRangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.Visita.visita[] @return;
        
        public findRangeResponse() {
        }
        
        public findRangeResponse(Carcel.Visita.visita[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="edit", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class editRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.Visita.visita entity;
        
        public editRequest() {
        }
        
        public editRequest(Carcel.Visita.visita entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class editResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public editResponse1() {
        }
        
        public editResponse1(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscar", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class buscarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public buscarRequest() {
        }
        
        public buscarRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class buscarResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.Visita.visita @return;
        
        public buscarResponse1() {
        }
        
        public buscarResponse1(Carcel.Visita.visita @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSVisitaChannel : Carcel.Visita.WSVisita, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSVisitaClient : System.ServiceModel.ClientBase<Carcel.Visita.WSVisita>, Carcel.Visita.WSVisita {
        
        public WSVisitaClient() {
        }
        
        public WSVisitaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSVisitaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSVisitaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSVisitaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.Visita.removeResponse1 Carcel.Visita.WSVisita.remove(Carcel.Visita.removeRequest request) {
            return base.Channel.remove(request);
        }
        
        public bool remove(Carcel.Visita.visita entity) {
            Carcel.Visita.removeRequest inValue = new Carcel.Visita.removeRequest();
            inValue.entity = entity;
            Carcel.Visita.removeResponse1 retVal = ((Carcel.Visita.WSVisita)(this)).remove(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.Visita.removeResponse1> Carcel.Visita.WSVisita.removeAsync(Carcel.Visita.removeRequest request) {
            return base.Channel.removeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.Visita.removeResponse1> removeAsync(Carcel.Visita.visita entity) {
            Carcel.Visita.removeRequest inValue = new Carcel.Visita.removeRequest();
            inValue.entity = entity;
            return ((Carcel.Visita.WSVisita)(this)).removeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.Visita.countResponse1 Carcel.Visita.WSVisita.count(Carcel.Visita.countRequest request) {
            return base.Channel.count(request);
        }
        
        public int count() {
            Carcel.Visita.countRequest inValue = new Carcel.Visita.countRequest();
            Carcel.Visita.countResponse1 retVal = ((Carcel.Visita.WSVisita)(this)).count(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.Visita.countResponse1> Carcel.Visita.WSVisita.countAsync(Carcel.Visita.countRequest request) {
            return base.Channel.countAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.Visita.countResponse1> countAsync() {
            Carcel.Visita.countRequest inValue = new Carcel.Visita.countRequest();
            return ((Carcel.Visita.WSVisita)(this)).countAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.Visita.findResponse1 Carcel.Visita.WSVisita.find(Carcel.Visita.findRequest request) {
            return base.Channel.find(request);
        }
        
        public Carcel.Visita.visita find(object id) {
            Carcel.Visita.findRequest inValue = new Carcel.Visita.findRequest();
            inValue.id = id;
            Carcel.Visita.findResponse1 retVal = ((Carcel.Visita.WSVisita)(this)).find(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.Visita.findResponse1> Carcel.Visita.WSVisita.findAsync(Carcel.Visita.findRequest request) {
            return base.Channel.findAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.Visita.findResponse1> findAsync(object id) {
            Carcel.Visita.findRequest inValue = new Carcel.Visita.findRequest();
            inValue.id = id;
            return ((Carcel.Visita.WSVisita)(this)).findAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.Visita.createResponse1 Carcel.Visita.WSVisita.create(Carcel.Visita.createRequest request) {
            return base.Channel.create(request);
        }
        
        public bool create(Carcel.Visita.visita entity) {
            Carcel.Visita.createRequest inValue = new Carcel.Visita.createRequest();
            inValue.entity = entity;
            Carcel.Visita.createResponse1 retVal = ((Carcel.Visita.WSVisita)(this)).create(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.Visita.createResponse1> Carcel.Visita.WSVisita.createAsync(Carcel.Visita.createRequest request) {
            return base.Channel.createAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.Visita.createResponse1> createAsync(Carcel.Visita.visita entity) {
            Carcel.Visita.createRequest inValue = new Carcel.Visita.createRequest();
            inValue.entity = entity;
            return ((Carcel.Visita.WSVisita)(this)).createAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.Visita.agregarVisitaResponse1 Carcel.Visita.WSVisita.agregarVisita(Carcel.Visita.agregarVisitaRequest request) {
            return base.Channel.agregarVisita(request);
        }
        
        public bool agregarVisita(string id, string observacion, int idPreso, string nombre, short edad, int idHorario) {
            Carcel.Visita.agregarVisitaRequest inValue = new Carcel.Visita.agregarVisitaRequest();
            inValue.id = id;
            inValue.observacion = observacion;
            inValue.idPreso = idPreso;
            inValue.nombre = nombre;
            inValue.edad = edad;
            inValue.idHorario = idHorario;
            Carcel.Visita.agregarVisitaResponse1 retVal = ((Carcel.Visita.WSVisita)(this)).agregarVisita(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.Visita.agregarVisitaResponse1> Carcel.Visita.WSVisita.agregarVisitaAsync(Carcel.Visita.agregarVisitaRequest request) {
            return base.Channel.agregarVisitaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.Visita.agregarVisitaResponse1> agregarVisitaAsync(string id, string observacion, int idPreso, string nombre, short edad, int idHorario) {
            Carcel.Visita.agregarVisitaRequest inValue = new Carcel.Visita.agregarVisitaRequest();
            inValue.id = id;
            inValue.observacion = observacion;
            inValue.idPreso = idPreso;
            inValue.nombre = nombre;
            inValue.edad = edad;
            inValue.idHorario = idHorario;
            return ((Carcel.Visita.WSVisita)(this)).agregarVisitaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.Visita.findAllResponse Carcel.Visita.WSVisita.findAll(Carcel.Visita.findAllRequest request) {
            return base.Channel.findAll(request);
        }
        
        public Carcel.Visita.visita[] findAll() {
            Carcel.Visita.findAllRequest inValue = new Carcel.Visita.findAllRequest();
            Carcel.Visita.findAllResponse retVal = ((Carcel.Visita.WSVisita)(this)).findAll(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.Visita.findAllResponse> Carcel.Visita.WSVisita.findAllAsync(Carcel.Visita.findAllRequest request) {
            return base.Channel.findAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.Visita.findAllResponse> findAllAsync() {
            Carcel.Visita.findAllRequest inValue = new Carcel.Visita.findAllRequest();
            return ((Carcel.Visita.WSVisita)(this)).findAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.Visita.findRangeResponse Carcel.Visita.WSVisita.findRange(Carcel.Visita.findRangeRequest request) {
            return base.Channel.findRange(request);
        }
        
        public Carcel.Visita.visita[] findRange(System.Nullable<int>[] range) {
            Carcel.Visita.findRangeRequest inValue = new Carcel.Visita.findRangeRequest();
            inValue.range = range;
            Carcel.Visita.findRangeResponse retVal = ((Carcel.Visita.WSVisita)(this)).findRange(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.Visita.findRangeResponse> Carcel.Visita.WSVisita.findRangeAsync(Carcel.Visita.findRangeRequest request) {
            return base.Channel.findRangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.Visita.findRangeResponse> findRangeAsync(System.Nullable<int>[] range) {
            Carcel.Visita.findRangeRequest inValue = new Carcel.Visita.findRangeRequest();
            inValue.range = range;
            return ((Carcel.Visita.WSVisita)(this)).findRangeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.Visita.editResponse1 Carcel.Visita.WSVisita.edit(Carcel.Visita.editRequest request) {
            return base.Channel.edit(request);
        }
        
        public bool edit(Carcel.Visita.visita entity) {
            Carcel.Visita.editRequest inValue = new Carcel.Visita.editRequest();
            inValue.entity = entity;
            Carcel.Visita.editResponse1 retVal = ((Carcel.Visita.WSVisita)(this)).edit(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.Visita.editResponse1> Carcel.Visita.WSVisita.editAsync(Carcel.Visita.editRequest request) {
            return base.Channel.editAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.Visita.editResponse1> editAsync(Carcel.Visita.visita entity) {
            Carcel.Visita.editRequest inValue = new Carcel.Visita.editRequest();
            inValue.entity = entity;
            return ((Carcel.Visita.WSVisita)(this)).editAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.Visita.buscarResponse1 Carcel.Visita.WSVisita.buscar(Carcel.Visita.buscarRequest request) {
            return base.Channel.buscar(request);
        }
        
        public Carcel.Visita.visita buscar(int id) {
            Carcel.Visita.buscarRequest inValue = new Carcel.Visita.buscarRequest();
            inValue.id = id;
            Carcel.Visita.buscarResponse1 retVal = ((Carcel.Visita.WSVisita)(this)).buscar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.Visita.buscarResponse1> Carcel.Visita.WSVisita.buscarAsync(Carcel.Visita.buscarRequest request) {
            return base.Channel.buscarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.Visita.buscarResponse1> buscarAsync(int id) {
            Carcel.Visita.buscarRequest inValue = new Carcel.Visita.buscarRequest();
            inValue.id = id;
            return ((Carcel.Visita.WSVisita)(this)).buscarAsync(inValue);
        }
    }
}
