//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carcel.penal {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service/", ConfigurationName="penal.WSPenal")]
    public interface WSPenal {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPenal/createPenalRequest", ReplyAction="http://service/WSPenal/createPenalResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPenal))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.penal.createPenalResponse1 createPenal(Carcel.penal.createPenalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPenal/createPenalRequest", ReplyAction="http://service/WSPenal/createPenalResponse")]
        System.Threading.Tasks.Task<Carcel.penal.createPenalResponse1> createPenalAsync(Carcel.penal.createPenalRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPenal/countPenalRequest", ReplyAction="http://service/WSPenal/countPenalResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPenal))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.penal.countPenalResponse1 countPenal(Carcel.penal.countPenalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPenal/countPenalRequest", ReplyAction="http://service/WSPenal/countPenalResponse")]
        System.Threading.Tasks.Task<Carcel.penal.countPenalResponse1> countPenalAsync(Carcel.penal.countPenalRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPenal/findPenalRequest", ReplyAction="http://service/WSPenal/findPenalResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPenal))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.penal.findPenalResponse1 findPenal(Carcel.penal.findPenalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPenal/findPenalRequest", ReplyAction="http://service/WSPenal/findPenalResponse")]
        System.Threading.Tasks.Task<Carcel.penal.findPenalResponse1> findPenalAsync(Carcel.penal.findPenalRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPenal/findAllPenalRequest", ReplyAction="http://service/WSPenal/findAllPenalResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPenal))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.penal.findAllPenalResponse findAllPenal(Carcel.penal.findAllPenalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPenal/findAllPenalRequest", ReplyAction="http://service/WSPenal/findAllPenalResponse")]
        System.Threading.Tasks.Task<Carcel.penal.findAllPenalResponse> findAllPenalAsync(Carcel.penal.findAllPenalRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPenal/removePenalRequest", ReplyAction="http://service/WSPenal/removePenalResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPenal))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.penal.removePenalResponse1 removePenal(Carcel.penal.removePenalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPenal/removePenalRequest", ReplyAction="http://service/WSPenal/removePenalResponse")]
        System.Threading.Tasks.Task<Carcel.penal.removePenalResponse1> removePenalAsync(Carcel.penal.removePenalRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPenal/buscarPenalRequest", ReplyAction="http://service/WSPenal/buscarPenalResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPenal))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.penal.buscarPenalResponse1 buscarPenal(Carcel.penal.buscarPenalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPenal/buscarPenalRequest", ReplyAction="http://service/WSPenal/buscarPenalResponse")]
        System.Threading.Tasks.Task<Carcel.penal.buscarPenalResponse1> buscarPenalAsync(Carcel.penal.buscarPenalRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPenal/editPenalRequest", ReplyAction="http://service/WSPenal/editPenalResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPenal))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.penal.editPenalResponse1 editPenal(Carcel.penal.editPenalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPenal/editPenalRequest", ReplyAction="http://service/WSPenal/editPenalResponse")]
        System.Threading.Tasks.Task<Carcel.penal.editPenalResponse1> editPenalAsync(Carcel.penal.editPenalRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPenal/findRangePenalRequest", ReplyAction="http://service/WSPenal/findRangePenalResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllPenal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPenalResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPenal))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.penal.findRangePenalResponse findRangePenal(Carcel.penal.findRangePenalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPenal/findRangePenalRequest", ReplyAction="http://service/WSPenal/findRangePenalResponse")]
        System.Threading.Tasks.Task<Carcel.penal.findRangePenalResponse> findRangePenalAsync(Carcel.penal.findRangePenalRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class penal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private short idPenalField;
        
        private bool idPenalFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public short idPenal {
            get {
                return this.idPenalField;
            }
            set {
                this.idPenalField = value;
                this.RaisePropertyChanged("idPenal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPenalSpecified {
            get {
                return this.idPenalFieldSpecified;
            }
            set {
                this.idPenalFieldSpecified = value;
                this.RaisePropertyChanged("idPenalSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class buscarPenalResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private penal returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public penal @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class buscarPenal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class countPenalResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class countPenal : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class editPenalResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class editPenal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private penal entityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public penal entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
                this.RaisePropertyChanged("entity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class removePenalResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class removePenal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private penal entityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public penal entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
                this.RaisePropertyChanged("entity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class findPenalResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private penal returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public penal @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class findPenal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class findAllPenal : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class createPenalResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class createPenal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private penal entityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public penal entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
                this.RaisePropertyChanged("entity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createPenal", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class createPenalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.penal.penal entity;
        
        public createPenalRequest() {
        }
        
        public createPenalRequest(Carcel.penal.penal entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createPenalResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class createPenalResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public createPenalResponse1() {
        }
        
        public createPenalResponse1(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="countPenal", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class countPenalRequest {
        
        public countPenalRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="countPenalResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class countPenalResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public countPenalResponse1() {
        }
        
        public countPenalResponse1(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findPenal", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findPenalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object id;
        
        public findPenalRequest() {
        }
        
        public findPenalRequest(object id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findPenalResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findPenalResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.penal.penal @return;
        
        public findPenalResponse1() {
        }
        
        public findPenalResponse1(Carcel.penal.penal @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllPenal", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findAllPenalRequest {
        
        public findAllPenalRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllPenalResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findAllPenalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.penal.penal[] @return;
        
        public findAllPenalResponse() {
        }
        
        public findAllPenalResponse(Carcel.penal.penal[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removePenal", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class removePenalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.penal.penal entity;
        
        public removePenalRequest() {
        }
        
        public removePenalRequest(Carcel.penal.penal entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removePenalResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class removePenalResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public removePenalResponse1() {
        }
        
        public removePenalResponse1(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarPenal", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class buscarPenalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public buscarPenalRequest() {
        }
        
        public buscarPenalRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarPenalResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class buscarPenalResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.penal.penal @return;
        
        public buscarPenalResponse1() {
        }
        
        public buscarPenalResponse1(Carcel.penal.penal @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editPenal", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class editPenalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.penal.penal entity;
        
        public editPenalRequest() {
        }
        
        public editPenalRequest(Carcel.penal.penal entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editPenalResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class editPenalResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public editPenalResponse1() {
        }
        
        public editPenalResponse1(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findRangePenal", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findRangePenalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("range", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int>[] range;
        
        public findRangePenalRequest() {
        }
        
        public findRangePenalRequest(System.Nullable<int>[] range) {
            this.range = range;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findRangePenalResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findRangePenalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.penal.penal[] @return;
        
        public findRangePenalResponse() {
        }
        
        public findRangePenalResponse(Carcel.penal.penal[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSPenalChannel : Carcel.penal.WSPenal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSPenalClient : System.ServiceModel.ClientBase<Carcel.penal.WSPenal>, Carcel.penal.WSPenal {
        
        public WSPenalClient() {
        }
        
        public WSPenalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSPenalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPenalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPenalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.penal.createPenalResponse1 Carcel.penal.WSPenal.createPenal(Carcel.penal.createPenalRequest request) {
            return base.Channel.createPenal(request);
        }
        
        public bool createPenal(Carcel.penal.penal entity) {
            Carcel.penal.createPenalRequest inValue = new Carcel.penal.createPenalRequest();
            inValue.entity = entity;
            Carcel.penal.createPenalResponse1 retVal = ((Carcel.penal.WSPenal)(this)).createPenal(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.penal.createPenalResponse1> Carcel.penal.WSPenal.createPenalAsync(Carcel.penal.createPenalRequest request) {
            return base.Channel.createPenalAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.penal.createPenalResponse1> createPenalAsync(Carcel.penal.penal entity) {
            Carcel.penal.createPenalRequest inValue = new Carcel.penal.createPenalRequest();
            inValue.entity = entity;
            return ((Carcel.penal.WSPenal)(this)).createPenalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.penal.countPenalResponse1 Carcel.penal.WSPenal.countPenal(Carcel.penal.countPenalRequest request) {
            return base.Channel.countPenal(request);
        }
        
        public int countPenal() {
            Carcel.penal.countPenalRequest inValue = new Carcel.penal.countPenalRequest();
            Carcel.penal.countPenalResponse1 retVal = ((Carcel.penal.WSPenal)(this)).countPenal(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.penal.countPenalResponse1> Carcel.penal.WSPenal.countPenalAsync(Carcel.penal.countPenalRequest request) {
            return base.Channel.countPenalAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.penal.countPenalResponse1> countPenalAsync() {
            Carcel.penal.countPenalRequest inValue = new Carcel.penal.countPenalRequest();
            return ((Carcel.penal.WSPenal)(this)).countPenalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.penal.findPenalResponse1 Carcel.penal.WSPenal.findPenal(Carcel.penal.findPenalRequest request) {
            return base.Channel.findPenal(request);
        }
        
        public Carcel.penal.penal findPenal(object id) {
            Carcel.penal.findPenalRequest inValue = new Carcel.penal.findPenalRequest();
            inValue.id = id;
            Carcel.penal.findPenalResponse1 retVal = ((Carcel.penal.WSPenal)(this)).findPenal(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.penal.findPenalResponse1> Carcel.penal.WSPenal.findPenalAsync(Carcel.penal.findPenalRequest request) {
            return base.Channel.findPenalAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.penal.findPenalResponse1> findPenalAsync(object id) {
            Carcel.penal.findPenalRequest inValue = new Carcel.penal.findPenalRequest();
            inValue.id = id;
            return ((Carcel.penal.WSPenal)(this)).findPenalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.penal.findAllPenalResponse Carcel.penal.WSPenal.findAllPenal(Carcel.penal.findAllPenalRequest request) {
            return base.Channel.findAllPenal(request);
        }
        
        public Carcel.penal.penal[] findAllPenal() {
            Carcel.penal.findAllPenalRequest inValue = new Carcel.penal.findAllPenalRequest();
            Carcel.penal.findAllPenalResponse retVal = ((Carcel.penal.WSPenal)(this)).findAllPenal(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.penal.findAllPenalResponse> Carcel.penal.WSPenal.findAllPenalAsync(Carcel.penal.findAllPenalRequest request) {
            return base.Channel.findAllPenalAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.penal.findAllPenalResponse> findAllPenalAsync() {
            Carcel.penal.findAllPenalRequest inValue = new Carcel.penal.findAllPenalRequest();
            return ((Carcel.penal.WSPenal)(this)).findAllPenalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.penal.removePenalResponse1 Carcel.penal.WSPenal.removePenal(Carcel.penal.removePenalRequest request) {
            return base.Channel.removePenal(request);
        }
        
        public bool removePenal(Carcel.penal.penal entity) {
            Carcel.penal.removePenalRequest inValue = new Carcel.penal.removePenalRequest();
            inValue.entity = entity;
            Carcel.penal.removePenalResponse1 retVal = ((Carcel.penal.WSPenal)(this)).removePenal(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.penal.removePenalResponse1> Carcel.penal.WSPenal.removePenalAsync(Carcel.penal.removePenalRequest request) {
            return base.Channel.removePenalAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.penal.removePenalResponse1> removePenalAsync(Carcel.penal.penal entity) {
            Carcel.penal.removePenalRequest inValue = new Carcel.penal.removePenalRequest();
            inValue.entity = entity;
            return ((Carcel.penal.WSPenal)(this)).removePenalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.penal.buscarPenalResponse1 Carcel.penal.WSPenal.buscarPenal(Carcel.penal.buscarPenalRequest request) {
            return base.Channel.buscarPenal(request);
        }
        
        public Carcel.penal.penal buscarPenal(int id) {
            Carcel.penal.buscarPenalRequest inValue = new Carcel.penal.buscarPenalRequest();
            inValue.id = id;
            Carcel.penal.buscarPenalResponse1 retVal = ((Carcel.penal.WSPenal)(this)).buscarPenal(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.penal.buscarPenalResponse1> Carcel.penal.WSPenal.buscarPenalAsync(Carcel.penal.buscarPenalRequest request) {
            return base.Channel.buscarPenalAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.penal.buscarPenalResponse1> buscarPenalAsync(int id) {
            Carcel.penal.buscarPenalRequest inValue = new Carcel.penal.buscarPenalRequest();
            inValue.id = id;
            return ((Carcel.penal.WSPenal)(this)).buscarPenalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.penal.editPenalResponse1 Carcel.penal.WSPenal.editPenal(Carcel.penal.editPenalRequest request) {
            return base.Channel.editPenal(request);
        }
        
        public bool editPenal(Carcel.penal.penal entity) {
            Carcel.penal.editPenalRequest inValue = new Carcel.penal.editPenalRequest();
            inValue.entity = entity;
            Carcel.penal.editPenalResponse1 retVal = ((Carcel.penal.WSPenal)(this)).editPenal(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.penal.editPenalResponse1> Carcel.penal.WSPenal.editPenalAsync(Carcel.penal.editPenalRequest request) {
            return base.Channel.editPenalAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.penal.editPenalResponse1> editPenalAsync(Carcel.penal.penal entity) {
            Carcel.penal.editPenalRequest inValue = new Carcel.penal.editPenalRequest();
            inValue.entity = entity;
            return ((Carcel.penal.WSPenal)(this)).editPenalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.penal.findRangePenalResponse Carcel.penal.WSPenal.findRangePenal(Carcel.penal.findRangePenalRequest request) {
            return base.Channel.findRangePenal(request);
        }
        
        public Carcel.penal.penal[] findRangePenal(System.Nullable<int>[] range) {
            Carcel.penal.findRangePenalRequest inValue = new Carcel.penal.findRangePenalRequest();
            inValue.range = range;
            Carcel.penal.findRangePenalResponse retVal = ((Carcel.penal.WSPenal)(this)).findRangePenal(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.penal.findRangePenalResponse> Carcel.penal.WSPenal.findRangePenalAsync(Carcel.penal.findRangePenalRequest request) {
            return base.Channel.findRangePenalAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.penal.findRangePenalResponse> findRangePenalAsync(System.Nullable<int>[] range) {
            Carcel.penal.findRangePenalRequest inValue = new Carcel.penal.findRangePenalRequest();
            inValue.range = range;
            return ((Carcel.penal.WSPenal)(this)).findRangePenalAsync(inValue);
        }
    }
}
