//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carcel.horario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service/", ConfigurationName="horario.WSHorario")]
    public interface WSHorario {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSHorario/createHorarioRequest", ReplyAction="http://service/WSHorario/createHorarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeHorario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.horario.createHorarioResponse1 createHorario(Carcel.horario.createHorarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSHorario/createHorarioRequest", ReplyAction="http://service/WSHorario/createHorarioResponse")]
        System.Threading.Tasks.Task<Carcel.horario.createHorarioResponse1> createHorarioAsync(Carcel.horario.createHorarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSHorario/countHorarioRequest", ReplyAction="http://service/WSHorario/countHorarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeHorario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.horario.countHorarioResponse1 countHorario(Carcel.horario.countHorarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSHorario/countHorarioRequest", ReplyAction="http://service/WSHorario/countHorarioResponse")]
        System.Threading.Tasks.Task<Carcel.horario.countHorarioResponse1> countHorarioAsync(Carcel.horario.countHorarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSHorario/findRangeHorarioRequest", ReplyAction="http://service/WSHorario/findRangeHorarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeHorario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.horario.findRangeHorarioResponse findRangeHorario(Carcel.horario.findRangeHorarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSHorario/findRangeHorarioRequest", ReplyAction="http://service/WSHorario/findRangeHorarioResponse")]
        System.Threading.Tasks.Task<Carcel.horario.findRangeHorarioResponse> findRangeHorarioAsync(Carcel.horario.findRangeHorarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSHorario/editHorarioRequest", ReplyAction="http://service/WSHorario/editHorarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeHorario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.horario.editHorarioResponse1 editHorario(Carcel.horario.editHorarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSHorario/editHorarioRequest", ReplyAction="http://service/WSHorario/editHorarioResponse")]
        System.Threading.Tasks.Task<Carcel.horario.editHorarioResponse1> editHorarioAsync(Carcel.horario.editHorarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSHorario/removeHorarioRequest", ReplyAction="http://service/WSHorario/removeHorarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeHorario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.horario.removeHorarioResponse1 removeHorario(Carcel.horario.removeHorarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSHorario/removeHorarioRequest", ReplyAction="http://service/WSHorario/removeHorarioResponse")]
        System.Threading.Tasks.Task<Carcel.horario.removeHorarioResponse1> removeHorarioAsync(Carcel.horario.removeHorarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSHorario/buscarHorarioRequest", ReplyAction="http://service/WSHorario/buscarHorarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeHorario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.horario.buscarHorarioResponse1 buscarHorario(Carcel.horario.buscarHorarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSHorario/buscarHorarioRequest", ReplyAction="http://service/WSHorario/buscarHorarioResponse")]
        System.Threading.Tasks.Task<Carcel.horario.buscarHorarioResponse1> buscarHorarioAsync(Carcel.horario.buscarHorarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSHorario/findAllHorarioRequest", ReplyAction="http://service/WSHorario/findAllHorarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeHorario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.horario.findAllHorarioResponse findAllHorario(Carcel.horario.findAllHorarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSHorario/findAllHorarioRequest", ReplyAction="http://service/WSHorario/findAllHorarioResponse")]
        System.Threading.Tasks.Task<Carcel.horario.findAllHorarioResponse> findAllHorarioAsync(Carcel.horario.findAllHorarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSHorario/findHorarioRequest", ReplyAction="http://service/WSHorario/findHorarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllHorario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeHorarioResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeHorario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.horario.findHorarioResponse1 findHorario(Carcel.horario.findHorarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSHorario/findHorarioRequest", ReplyAction="http://service/WSHorario/findHorarioResponse")]
        System.Threading.Tasks.Task<Carcel.horario.findHorarioResponse1> findHorarioAsync(Carcel.horario.findHorarioRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class horario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionHField;
        
        private short idHorarioField;
        
        private bool idHorarioFieldSpecified;
        
        private short minutosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionH {
            get {
                return this.descripcionHField;
            }
            set {
                this.descripcionHField = value;
                this.RaisePropertyChanged("descripcionH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public short idHorario {
            get {
                return this.idHorarioField;
            }
            set {
                this.idHorarioField = value;
                this.RaisePropertyChanged("idHorario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idHorarioSpecified {
            get {
                return this.idHorarioFieldSpecified;
            }
            set {
                this.idHorarioFieldSpecified = value;
                this.RaisePropertyChanged("idHorarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public short minutos {
            get {
                return this.minutosField;
            }
            set {
                this.minutosField = value;
                this.RaisePropertyChanged("minutos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class editHorarioResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class editHorario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private horario entityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public horario entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
                this.RaisePropertyChanged("entity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class createHorarioResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class createHorario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private horario entityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public horario entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
                this.RaisePropertyChanged("entity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class countHorarioResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class countHorario : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class buscarHorarioResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private horario returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public horario @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class buscarHorario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class findHorarioResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private horario returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public horario @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class findHorario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class findAllHorario : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class removeHorarioResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class removeHorario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private horario entityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public horario entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
                this.RaisePropertyChanged("entity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createHorario", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class createHorarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.horario.horario entity;
        
        public createHorarioRequest() {
        }
        
        public createHorarioRequest(Carcel.horario.horario entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createHorarioResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class createHorarioResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public createHorarioResponse1() {
        }
        
        public createHorarioResponse1(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="countHorario", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class countHorarioRequest {
        
        public countHorarioRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="countHorarioResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class countHorarioResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public countHorarioResponse1() {
        }
        
        public countHorarioResponse1(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findRangeHorario", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findRangeHorarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("range", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int>[] range;
        
        public findRangeHorarioRequest() {
        }
        
        public findRangeHorarioRequest(System.Nullable<int>[] range) {
            this.range = range;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findRangeHorarioResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findRangeHorarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.horario.horario[] @return;
        
        public findRangeHorarioResponse() {
        }
        
        public findRangeHorarioResponse(Carcel.horario.horario[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editHorario", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class editHorarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.horario.horario entity;
        
        public editHorarioRequest() {
        }
        
        public editHorarioRequest(Carcel.horario.horario entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editHorarioResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class editHorarioResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public editHorarioResponse1() {
        }
        
        public editHorarioResponse1(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeHorario", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class removeHorarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.horario.horario entity;
        
        public removeHorarioRequest() {
        }
        
        public removeHorarioRequest(Carcel.horario.horario entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeHorarioResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class removeHorarioResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public removeHorarioResponse1() {
        }
        
        public removeHorarioResponse1(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarHorario", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class buscarHorarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public buscarHorarioRequest() {
        }
        
        public buscarHorarioRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarHorarioResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class buscarHorarioResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.horario.horario @return;
        
        public buscarHorarioResponse1() {
        }
        
        public buscarHorarioResponse1(Carcel.horario.horario @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllHorario", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findAllHorarioRequest {
        
        public findAllHorarioRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllHorarioResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findAllHorarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.horario.horario[] @return;
        
        public findAllHorarioResponse() {
        }
        
        public findAllHorarioResponse(Carcel.horario.horario[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findHorario", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findHorarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object id;
        
        public findHorarioRequest() {
        }
        
        public findHorarioRequest(object id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findHorarioResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findHorarioResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.horario.horario @return;
        
        public findHorarioResponse1() {
        }
        
        public findHorarioResponse1(Carcel.horario.horario @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSHorarioChannel : Carcel.horario.WSHorario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSHorarioClient : System.ServiceModel.ClientBase<Carcel.horario.WSHorario>, Carcel.horario.WSHorario {
        
        public WSHorarioClient() {
        }
        
        public WSHorarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSHorarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSHorarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSHorarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.horario.createHorarioResponse1 Carcel.horario.WSHorario.createHorario(Carcel.horario.createHorarioRequest request) {
            return base.Channel.createHorario(request);
        }
        
        public bool createHorario(Carcel.horario.horario entity) {
            Carcel.horario.createHorarioRequest inValue = new Carcel.horario.createHorarioRequest();
            inValue.entity = entity;
            Carcel.horario.createHorarioResponse1 retVal = ((Carcel.horario.WSHorario)(this)).createHorario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.horario.createHorarioResponse1> Carcel.horario.WSHorario.createHorarioAsync(Carcel.horario.createHorarioRequest request) {
            return base.Channel.createHorarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.horario.createHorarioResponse1> createHorarioAsync(Carcel.horario.horario entity) {
            Carcel.horario.createHorarioRequest inValue = new Carcel.horario.createHorarioRequest();
            inValue.entity = entity;
            return ((Carcel.horario.WSHorario)(this)).createHorarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.horario.countHorarioResponse1 Carcel.horario.WSHorario.countHorario(Carcel.horario.countHorarioRequest request) {
            return base.Channel.countHorario(request);
        }
        
        public int countHorario() {
            Carcel.horario.countHorarioRequest inValue = new Carcel.horario.countHorarioRequest();
            Carcel.horario.countHorarioResponse1 retVal = ((Carcel.horario.WSHorario)(this)).countHorario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.horario.countHorarioResponse1> Carcel.horario.WSHorario.countHorarioAsync(Carcel.horario.countHorarioRequest request) {
            return base.Channel.countHorarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.horario.countHorarioResponse1> countHorarioAsync() {
            Carcel.horario.countHorarioRequest inValue = new Carcel.horario.countHorarioRequest();
            return ((Carcel.horario.WSHorario)(this)).countHorarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.horario.findRangeHorarioResponse Carcel.horario.WSHorario.findRangeHorario(Carcel.horario.findRangeHorarioRequest request) {
            return base.Channel.findRangeHorario(request);
        }
        
        public Carcel.horario.horario[] findRangeHorario(System.Nullable<int>[] range) {
            Carcel.horario.findRangeHorarioRequest inValue = new Carcel.horario.findRangeHorarioRequest();
            inValue.range = range;
            Carcel.horario.findRangeHorarioResponse retVal = ((Carcel.horario.WSHorario)(this)).findRangeHorario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.horario.findRangeHorarioResponse> Carcel.horario.WSHorario.findRangeHorarioAsync(Carcel.horario.findRangeHorarioRequest request) {
            return base.Channel.findRangeHorarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.horario.findRangeHorarioResponse> findRangeHorarioAsync(System.Nullable<int>[] range) {
            Carcel.horario.findRangeHorarioRequest inValue = new Carcel.horario.findRangeHorarioRequest();
            inValue.range = range;
            return ((Carcel.horario.WSHorario)(this)).findRangeHorarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.horario.editHorarioResponse1 Carcel.horario.WSHorario.editHorario(Carcel.horario.editHorarioRequest request) {
            return base.Channel.editHorario(request);
        }
        
        public bool editHorario(Carcel.horario.horario entity) {
            Carcel.horario.editHorarioRequest inValue = new Carcel.horario.editHorarioRequest();
            inValue.entity = entity;
            Carcel.horario.editHorarioResponse1 retVal = ((Carcel.horario.WSHorario)(this)).editHorario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.horario.editHorarioResponse1> Carcel.horario.WSHorario.editHorarioAsync(Carcel.horario.editHorarioRequest request) {
            return base.Channel.editHorarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.horario.editHorarioResponse1> editHorarioAsync(Carcel.horario.horario entity) {
            Carcel.horario.editHorarioRequest inValue = new Carcel.horario.editHorarioRequest();
            inValue.entity = entity;
            return ((Carcel.horario.WSHorario)(this)).editHorarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.horario.removeHorarioResponse1 Carcel.horario.WSHorario.removeHorario(Carcel.horario.removeHorarioRequest request) {
            return base.Channel.removeHorario(request);
        }
        
        public bool removeHorario(Carcel.horario.horario entity) {
            Carcel.horario.removeHorarioRequest inValue = new Carcel.horario.removeHorarioRequest();
            inValue.entity = entity;
            Carcel.horario.removeHorarioResponse1 retVal = ((Carcel.horario.WSHorario)(this)).removeHorario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.horario.removeHorarioResponse1> Carcel.horario.WSHorario.removeHorarioAsync(Carcel.horario.removeHorarioRequest request) {
            return base.Channel.removeHorarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.horario.removeHorarioResponse1> removeHorarioAsync(Carcel.horario.horario entity) {
            Carcel.horario.removeHorarioRequest inValue = new Carcel.horario.removeHorarioRequest();
            inValue.entity = entity;
            return ((Carcel.horario.WSHorario)(this)).removeHorarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.horario.buscarHorarioResponse1 Carcel.horario.WSHorario.buscarHorario(Carcel.horario.buscarHorarioRequest request) {
            return base.Channel.buscarHorario(request);
        }
        
        public Carcel.horario.horario buscarHorario(int id) {
            Carcel.horario.buscarHorarioRequest inValue = new Carcel.horario.buscarHorarioRequest();
            inValue.id = id;
            Carcel.horario.buscarHorarioResponse1 retVal = ((Carcel.horario.WSHorario)(this)).buscarHorario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.horario.buscarHorarioResponse1> Carcel.horario.WSHorario.buscarHorarioAsync(Carcel.horario.buscarHorarioRequest request) {
            return base.Channel.buscarHorarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.horario.buscarHorarioResponse1> buscarHorarioAsync(int id) {
            Carcel.horario.buscarHorarioRequest inValue = new Carcel.horario.buscarHorarioRequest();
            inValue.id = id;
            return ((Carcel.horario.WSHorario)(this)).buscarHorarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.horario.findAllHorarioResponse Carcel.horario.WSHorario.findAllHorario(Carcel.horario.findAllHorarioRequest request) {
            return base.Channel.findAllHorario(request);
        }
        
        public Carcel.horario.horario[] findAllHorario() {
            Carcel.horario.findAllHorarioRequest inValue = new Carcel.horario.findAllHorarioRequest();
            Carcel.horario.findAllHorarioResponse retVal = ((Carcel.horario.WSHorario)(this)).findAllHorario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.horario.findAllHorarioResponse> Carcel.horario.WSHorario.findAllHorarioAsync(Carcel.horario.findAllHorarioRequest request) {
            return base.Channel.findAllHorarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.horario.findAllHorarioResponse> findAllHorarioAsync() {
            Carcel.horario.findAllHorarioRequest inValue = new Carcel.horario.findAllHorarioRequest();
            return ((Carcel.horario.WSHorario)(this)).findAllHorarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.horario.findHorarioResponse1 Carcel.horario.WSHorario.findHorario(Carcel.horario.findHorarioRequest request) {
            return base.Channel.findHorario(request);
        }
        
        public Carcel.horario.horario findHorario(object id) {
            Carcel.horario.findHorarioRequest inValue = new Carcel.horario.findHorarioRequest();
            inValue.id = id;
            Carcel.horario.findHorarioResponse1 retVal = ((Carcel.horario.WSHorario)(this)).findHorario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.horario.findHorarioResponse1> Carcel.horario.WSHorario.findHorarioAsync(Carcel.horario.findHorarioRequest request) {
            return base.Channel.findHorarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.horario.findHorarioResponse1> findHorarioAsync(object id) {
            Carcel.horario.findHorarioRequest inValue = new Carcel.horario.findHorarioRequest();
            inValue.id = id;
            return ((Carcel.horario.WSHorario)(this)).findHorarioAsync(inValue);
        }
    }
}
