//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carcel.preso {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service/", ConfigurationName="preso.WSPreso")]
    public interface WSPreso {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPreso/findPresoRequest", ReplyAction="http://service/WSPreso/findPresoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarTodo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(actualizarpresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(actualizarpreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPreso))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.preso.findPresoResponse1 findPreso(Carcel.preso.findPresoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPreso/findPresoRequest", ReplyAction="http://service/WSPreso/findPresoResponse")]
        System.Threading.Tasks.Task<Carcel.preso.findPresoResponse1> findPresoAsync(Carcel.preso.findPresoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPreso/buscarPresoRequest", ReplyAction="http://service/WSPreso/buscarPresoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarTodo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(actualizarpresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(actualizarpreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPreso))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.preso.buscarPresoResponse1 buscarPreso(Carcel.preso.buscarPresoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPreso/buscarPresoRequest", ReplyAction="http://service/WSPreso/buscarPresoResponse")]
        System.Threading.Tasks.Task<Carcel.preso.buscarPresoResponse1> buscarPresoAsync(Carcel.preso.buscarPresoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPreso/countPresoRequest", ReplyAction="http://service/WSPreso/countPresoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarTodo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(actualizarpresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(actualizarpreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPreso))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.preso.countPresoResponse1 countPreso(Carcel.preso.countPresoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPreso/countPresoRequest", ReplyAction="http://service/WSPreso/countPresoResponse")]
        System.Threading.Tasks.Task<Carcel.preso.countPresoResponse1> countPresoAsync(Carcel.preso.countPresoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPreso/findRangePresoRequest", ReplyAction="http://service/WSPreso/findRangePresoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarTodo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(actualizarpresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(actualizarpreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPreso))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.preso.findRangePresoResponse findRangePreso(Carcel.preso.findRangePresoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPreso/findRangePresoRequest", ReplyAction="http://service/WSPreso/findRangePresoResponse")]
        System.Threading.Tasks.Task<Carcel.preso.findRangePresoResponse> findRangePresoAsync(Carcel.preso.findRangePresoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPreso/createPresoRequest", ReplyAction="http://service/WSPreso/createPresoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarTodo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(actualizarpresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(actualizarpreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPreso))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.preso.createPresoResponse1 createPreso(Carcel.preso.createPresoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPreso/createPresoRequest", ReplyAction="http://service/WSPreso/createPresoResponse")]
        System.Threading.Tasks.Task<Carcel.preso.createPresoResponse1> createPresoAsync(Carcel.preso.createPresoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPreso/editPresoRequest", ReplyAction="http://service/WSPreso/editPresoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarTodo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(actualizarpresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(actualizarpreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPreso))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.preso.editPresoResponse1 editPreso(Carcel.preso.editPresoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPreso/editPresoRequest", ReplyAction="http://service/WSPreso/editPresoResponse")]
        System.Threading.Tasks.Task<Carcel.preso.editPresoResponse1> editPresoAsync(Carcel.preso.editPresoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPreso/removePresoRequest", ReplyAction="http://service/WSPreso/removePresoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarTodo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(actualizarpresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(actualizarpreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPreso))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.preso.removePresoResponse1 removePreso(Carcel.preso.removePresoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPreso/removePresoRequest", ReplyAction="http://service/WSPreso/removePresoResponse")]
        System.Threading.Tasks.Task<Carcel.preso.removePresoResponse1> removePresoAsync(Carcel.preso.removePresoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPreso/findAllPresoRequest", ReplyAction="http://service/WSPreso/findAllPresoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarTodo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(actualizarpresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(actualizarpreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPreso))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.preso.findAllPresoResponse findAllPreso(Carcel.preso.findAllPresoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPreso/findAllPresoRequest", ReplyAction="http://service/WSPreso/findAllPresoResponse")]
        System.Threading.Tasks.Task<Carcel.preso.findAllPresoResponse> findAllPresoAsync(Carcel.preso.findAllPresoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPreso/AgregarPresoRequest", ReplyAction="http://service/WSPreso/AgregarPresoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarTodo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(actualizarpresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(actualizarpreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPreso))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.preso.AgregarPresoResponse1 AgregarPreso(Carcel.preso.AgregarPresoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPreso/AgregarPresoRequest", ReplyAction="http://service/WSPreso/AgregarPresoResponse")]
        System.Threading.Tasks.Task<Carcel.preso.AgregarPresoResponse1> AgregarPresoAsync(Carcel.preso.AgregarPresoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPreso/listarTodoRequest", ReplyAction="http://service/WSPreso/listarTodoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarTodo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(actualizarpresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(actualizarpreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPreso))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.preso.listarTodoResponse listarTodo(Carcel.preso.listarTodoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPreso/listarTodoRequest", ReplyAction="http://service/WSPreso/listarTodoResponse")]
        System.Threading.Tasks.Task<Carcel.preso.listarTodoResponse> listarTodoAsync(Carcel.preso.listarTodoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPreso/actualizarpresoRequest", ReplyAction="http://service/WSPreso/actualizarpresoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removePreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(createPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarTodo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(actualizarpresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(actualizarpreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AgregarPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countPreso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPresoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findPreso))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Carcel.preso.actualizarpresoResponse1 actualizarpreso(Carcel.preso.actualizarpresoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/WSPreso/actualizarpresoRequest", ReplyAction="http://service/WSPreso/actualizarpresoResponse")]
        System.Threading.Tasks.Task<Carcel.preso.actualizarpresoResponse1> actualizarpresoAsync(Carcel.preso.actualizarpresoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class removePresoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class removePreso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private preso entityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public preso entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
                this.RaisePropertyChanged("entity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class preso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short idPresoField;
        
        private bool idPresoFieldSpecified;
        
        private string nombreVField;
        
        private penal penalIdPenalField;
        
        private ushort sexoVField;
        
        private bool sexoVFieldSpecified;
        
        private ushort visitaVField;
        
        private bool visitaVFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public short idPreso {
            get {
                return this.idPresoField;
            }
            set {
                this.idPresoField = value;
                this.RaisePropertyChanged("idPreso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPresoSpecified {
            get {
                return this.idPresoFieldSpecified;
            }
            set {
                this.idPresoFieldSpecified = value;
                this.RaisePropertyChanged("idPresoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombreV {
            get {
                return this.nombreVField;
            }
            set {
                this.nombreVField = value;
                this.RaisePropertyChanged("nombreV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public penal penalIdPenal {
            get {
                return this.penalIdPenalField;
            }
            set {
                this.penalIdPenalField = value;
                this.RaisePropertyChanged("penalIdPenal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ushort sexoV {
            get {
                return this.sexoVField;
            }
            set {
                this.sexoVField = value;
                this.RaisePropertyChanged("sexoV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sexoVSpecified {
            get {
                return this.sexoVFieldSpecified;
            }
            set {
                this.sexoVFieldSpecified = value;
                this.RaisePropertyChanged("sexoVSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public ushort visitaV {
            get {
                return this.visitaVField;
            }
            set {
                this.visitaVField = value;
                this.RaisePropertyChanged("visitaV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool visitaVSpecified {
            get {
                return this.visitaVFieldSpecified;
            }
            set {
                this.visitaVFieldSpecified = value;
                this.RaisePropertyChanged("visitaVSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class penal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private short idPenalField;
        
        private bool idPenalFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public short idPenal {
            get {
                return this.idPenalField;
            }
            set {
                this.idPenalField = value;
                this.RaisePropertyChanged("idPenal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPenalSpecified {
            get {
                return this.idPenalFieldSpecified;
            }
            set {
                this.idPenalFieldSpecified = value;
                this.RaisePropertyChanged("idPenalSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class editPresoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class editPreso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private preso entityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public preso entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
                this.RaisePropertyChanged("entity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class findAllPreso : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class createPresoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class createPreso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private preso entityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public preso entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
                this.RaisePropertyChanged("entity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class listarTodo : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class actualizarpresoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class actualizarpreso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short idField;
        
        private string nombreField;
        
        private ushort sexoField;
        
        private ushort visitaField;
        
        private int penalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public short id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ushort sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ushort visita {
            get {
                return this.visitaField;
            }
            set {
                this.visitaField = value;
                this.RaisePropertyChanged("visita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int penal {
            get {
                return this.penalField;
            }
            set {
                this.penalField = value;
                this.RaisePropertyChanged("penal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class AgregarPresoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class AgregarPreso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nombreField;
        
        private ushort sexoField;
        
        private ushort visitaField;
        
        private int penalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ushort sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ushort visita {
            get {
                return this.visitaField;
            }
            set {
                this.visitaField = value;
                this.RaisePropertyChanged("visita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int penal {
            get {
                return this.penalField;
            }
            set {
                this.penalField = value;
                this.RaisePropertyChanged("penal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class buscarPresoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private preso returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public preso @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class buscarPreso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class countPresoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class countPreso : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class findPresoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private preso returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public preso @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class findPreso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findPreso", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findPresoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object id;
        
        public findPresoRequest() {
        }
        
        public findPresoRequest(object id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findPresoResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findPresoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.preso.preso @return;
        
        public findPresoResponse1() {
        }
        
        public findPresoResponse1(Carcel.preso.preso @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarPreso", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class buscarPresoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public buscarPresoRequest() {
        }
        
        public buscarPresoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarPresoResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class buscarPresoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.preso.preso @return;
        
        public buscarPresoResponse1() {
        }
        
        public buscarPresoResponse1(Carcel.preso.preso @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="countPreso", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class countPresoRequest {
        
        public countPresoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="countPresoResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class countPresoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public countPresoResponse1() {
        }
        
        public countPresoResponse1(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findRangePreso", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findRangePresoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("range", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int>[] range;
        
        public findRangePresoRequest() {
        }
        
        public findRangePresoRequest(System.Nullable<int>[] range) {
            this.range = range;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findRangePresoResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findRangePresoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.preso.preso[] @return;
        
        public findRangePresoResponse() {
        }
        
        public findRangePresoResponse(Carcel.preso.preso[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createPreso", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class createPresoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.preso.preso entity;
        
        public createPresoRequest() {
        }
        
        public createPresoRequest(Carcel.preso.preso entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createPresoResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class createPresoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public createPresoResponse1() {
        }
        
        public createPresoResponse1(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editPreso", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class editPresoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.preso.preso entity;
        
        public editPresoRequest() {
        }
        
        public editPresoRequest(Carcel.preso.preso entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editPresoResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class editPresoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public editPresoResponse1() {
        }
        
        public editPresoResponse1(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removePreso", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class removePresoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.preso.preso entity;
        
        public removePresoRequest() {
        }
        
        public removePresoRequest(Carcel.preso.preso entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removePresoResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class removePresoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public removePresoResponse1() {
        }
        
        public removePresoResponse1(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllPreso", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findAllPresoRequest {
        
        public findAllPresoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllPresoResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class findAllPresoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.preso.preso[] @return;
        
        public findAllPresoResponse() {
        }
        
        public findAllPresoResponse(Carcel.preso.preso[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarPreso", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class AgregarPresoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ushort sexo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ushort visita;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int penal;
        
        public AgregarPresoRequest() {
        }
        
        public AgregarPresoRequest(string id, string nombre, ushort sexo, ushort visita, int penal) {
            this.id = id;
            this.nombre = nombre;
            this.sexo = sexo;
            this.visita = visita;
            this.penal = penal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarPresoResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class AgregarPresoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public AgregarPresoResponse1() {
        }
        
        public AgregarPresoResponse1(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodo", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class listarTodoRequest {
        
        public listarTodoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodoResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class listarTodoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Carcel.preso.preso[] @return;
        
        public listarTodoResponse() {
        }
        
        public listarTodoResponse(Carcel.preso.preso[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarpreso", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class actualizarpresoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ushort sexo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ushort visita;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int penal;
        
        public actualizarpresoRequest() {
        }
        
        public actualizarpresoRequest(short id, string nombre, ushort sexo, ushort visita, int penal) {
            this.id = id;
            this.nombre = nombre;
            this.sexo = sexo;
            this.visita = visita;
            this.penal = penal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarpresoResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class actualizarpresoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public actualizarpresoResponse1() {
        }
        
        public actualizarpresoResponse1(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSPresoChannel : Carcel.preso.WSPreso, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSPresoClient : System.ServiceModel.ClientBase<Carcel.preso.WSPreso>, Carcel.preso.WSPreso {
        
        public WSPresoClient() {
        }
        
        public WSPresoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSPresoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPresoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPresoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.preso.findPresoResponse1 Carcel.preso.WSPreso.findPreso(Carcel.preso.findPresoRequest request) {
            return base.Channel.findPreso(request);
        }
        
        public Carcel.preso.preso findPreso(object id) {
            Carcel.preso.findPresoRequest inValue = new Carcel.preso.findPresoRequest();
            inValue.id = id;
            Carcel.preso.findPresoResponse1 retVal = ((Carcel.preso.WSPreso)(this)).findPreso(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.preso.findPresoResponse1> Carcel.preso.WSPreso.findPresoAsync(Carcel.preso.findPresoRequest request) {
            return base.Channel.findPresoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.preso.findPresoResponse1> findPresoAsync(object id) {
            Carcel.preso.findPresoRequest inValue = new Carcel.preso.findPresoRequest();
            inValue.id = id;
            return ((Carcel.preso.WSPreso)(this)).findPresoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.preso.buscarPresoResponse1 Carcel.preso.WSPreso.buscarPreso(Carcel.preso.buscarPresoRequest request) {
            return base.Channel.buscarPreso(request);
        }
        
        public Carcel.preso.preso buscarPreso(int id) {
            Carcel.preso.buscarPresoRequest inValue = new Carcel.preso.buscarPresoRequest();
            inValue.id = id;
            Carcel.preso.buscarPresoResponse1 retVal = ((Carcel.preso.WSPreso)(this)).buscarPreso(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.preso.buscarPresoResponse1> Carcel.preso.WSPreso.buscarPresoAsync(Carcel.preso.buscarPresoRequest request) {
            return base.Channel.buscarPresoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.preso.buscarPresoResponse1> buscarPresoAsync(int id) {
            Carcel.preso.buscarPresoRequest inValue = new Carcel.preso.buscarPresoRequest();
            inValue.id = id;
            return ((Carcel.preso.WSPreso)(this)).buscarPresoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.preso.countPresoResponse1 Carcel.preso.WSPreso.countPreso(Carcel.preso.countPresoRequest request) {
            return base.Channel.countPreso(request);
        }
        
        public int countPreso() {
            Carcel.preso.countPresoRequest inValue = new Carcel.preso.countPresoRequest();
            Carcel.preso.countPresoResponse1 retVal = ((Carcel.preso.WSPreso)(this)).countPreso(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.preso.countPresoResponse1> Carcel.preso.WSPreso.countPresoAsync(Carcel.preso.countPresoRequest request) {
            return base.Channel.countPresoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.preso.countPresoResponse1> countPresoAsync() {
            Carcel.preso.countPresoRequest inValue = new Carcel.preso.countPresoRequest();
            return ((Carcel.preso.WSPreso)(this)).countPresoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.preso.findRangePresoResponse Carcel.preso.WSPreso.findRangePreso(Carcel.preso.findRangePresoRequest request) {
            return base.Channel.findRangePreso(request);
        }
        
        public Carcel.preso.preso[] findRangePreso(System.Nullable<int>[] range) {
            Carcel.preso.findRangePresoRequest inValue = new Carcel.preso.findRangePresoRequest();
            inValue.range = range;
            Carcel.preso.findRangePresoResponse retVal = ((Carcel.preso.WSPreso)(this)).findRangePreso(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.preso.findRangePresoResponse> Carcel.preso.WSPreso.findRangePresoAsync(Carcel.preso.findRangePresoRequest request) {
            return base.Channel.findRangePresoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.preso.findRangePresoResponse> findRangePresoAsync(System.Nullable<int>[] range) {
            Carcel.preso.findRangePresoRequest inValue = new Carcel.preso.findRangePresoRequest();
            inValue.range = range;
            return ((Carcel.preso.WSPreso)(this)).findRangePresoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.preso.createPresoResponse1 Carcel.preso.WSPreso.createPreso(Carcel.preso.createPresoRequest request) {
            return base.Channel.createPreso(request);
        }
        
        public bool createPreso(Carcel.preso.preso entity) {
            Carcel.preso.createPresoRequest inValue = new Carcel.preso.createPresoRequest();
            inValue.entity = entity;
            Carcel.preso.createPresoResponse1 retVal = ((Carcel.preso.WSPreso)(this)).createPreso(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.preso.createPresoResponse1> Carcel.preso.WSPreso.createPresoAsync(Carcel.preso.createPresoRequest request) {
            return base.Channel.createPresoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.preso.createPresoResponse1> createPresoAsync(Carcel.preso.preso entity) {
            Carcel.preso.createPresoRequest inValue = new Carcel.preso.createPresoRequest();
            inValue.entity = entity;
            return ((Carcel.preso.WSPreso)(this)).createPresoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.preso.editPresoResponse1 Carcel.preso.WSPreso.editPreso(Carcel.preso.editPresoRequest request) {
            return base.Channel.editPreso(request);
        }
        
        public bool editPreso(Carcel.preso.preso entity) {
            Carcel.preso.editPresoRequest inValue = new Carcel.preso.editPresoRequest();
            inValue.entity = entity;
            Carcel.preso.editPresoResponse1 retVal = ((Carcel.preso.WSPreso)(this)).editPreso(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.preso.editPresoResponse1> Carcel.preso.WSPreso.editPresoAsync(Carcel.preso.editPresoRequest request) {
            return base.Channel.editPresoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.preso.editPresoResponse1> editPresoAsync(Carcel.preso.preso entity) {
            Carcel.preso.editPresoRequest inValue = new Carcel.preso.editPresoRequest();
            inValue.entity = entity;
            return ((Carcel.preso.WSPreso)(this)).editPresoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.preso.removePresoResponse1 Carcel.preso.WSPreso.removePreso(Carcel.preso.removePresoRequest request) {
            return base.Channel.removePreso(request);
        }
        
        public bool removePreso(Carcel.preso.preso entity) {
            Carcel.preso.removePresoRequest inValue = new Carcel.preso.removePresoRequest();
            inValue.entity = entity;
            Carcel.preso.removePresoResponse1 retVal = ((Carcel.preso.WSPreso)(this)).removePreso(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.preso.removePresoResponse1> Carcel.preso.WSPreso.removePresoAsync(Carcel.preso.removePresoRequest request) {
            return base.Channel.removePresoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.preso.removePresoResponse1> removePresoAsync(Carcel.preso.preso entity) {
            Carcel.preso.removePresoRequest inValue = new Carcel.preso.removePresoRequest();
            inValue.entity = entity;
            return ((Carcel.preso.WSPreso)(this)).removePresoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.preso.findAllPresoResponse Carcel.preso.WSPreso.findAllPreso(Carcel.preso.findAllPresoRequest request) {
            return base.Channel.findAllPreso(request);
        }
        
        public Carcel.preso.preso[] findAllPreso() {
            Carcel.preso.findAllPresoRequest inValue = new Carcel.preso.findAllPresoRequest();
            Carcel.preso.findAllPresoResponse retVal = ((Carcel.preso.WSPreso)(this)).findAllPreso(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.preso.findAllPresoResponse> Carcel.preso.WSPreso.findAllPresoAsync(Carcel.preso.findAllPresoRequest request) {
            return base.Channel.findAllPresoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.preso.findAllPresoResponse> findAllPresoAsync() {
            Carcel.preso.findAllPresoRequest inValue = new Carcel.preso.findAllPresoRequest();
            return ((Carcel.preso.WSPreso)(this)).findAllPresoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.preso.AgregarPresoResponse1 Carcel.preso.WSPreso.AgregarPreso(Carcel.preso.AgregarPresoRequest request) {
            return base.Channel.AgregarPreso(request);
        }
        
        public bool AgregarPreso(string id, string nombre, ushort sexo, ushort visita, int penal) {
            Carcel.preso.AgregarPresoRequest inValue = new Carcel.preso.AgregarPresoRequest();
            inValue.id = id;
            inValue.nombre = nombre;
            inValue.sexo = sexo;
            inValue.visita = visita;
            inValue.penal = penal;
            Carcel.preso.AgregarPresoResponse1 retVal = ((Carcel.preso.WSPreso)(this)).AgregarPreso(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.preso.AgregarPresoResponse1> Carcel.preso.WSPreso.AgregarPresoAsync(Carcel.preso.AgregarPresoRequest request) {
            return base.Channel.AgregarPresoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.preso.AgregarPresoResponse1> AgregarPresoAsync(string id, string nombre, ushort sexo, ushort visita, int penal) {
            Carcel.preso.AgregarPresoRequest inValue = new Carcel.preso.AgregarPresoRequest();
            inValue.id = id;
            inValue.nombre = nombre;
            inValue.sexo = sexo;
            inValue.visita = visita;
            inValue.penal = penal;
            return ((Carcel.preso.WSPreso)(this)).AgregarPresoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.preso.listarTodoResponse Carcel.preso.WSPreso.listarTodo(Carcel.preso.listarTodoRequest request) {
            return base.Channel.listarTodo(request);
        }
        
        public Carcel.preso.preso[] listarTodo() {
            Carcel.preso.listarTodoRequest inValue = new Carcel.preso.listarTodoRequest();
            Carcel.preso.listarTodoResponse retVal = ((Carcel.preso.WSPreso)(this)).listarTodo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.preso.listarTodoResponse> Carcel.preso.WSPreso.listarTodoAsync(Carcel.preso.listarTodoRequest request) {
            return base.Channel.listarTodoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.preso.listarTodoResponse> listarTodoAsync() {
            Carcel.preso.listarTodoRequest inValue = new Carcel.preso.listarTodoRequest();
            return ((Carcel.preso.WSPreso)(this)).listarTodoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carcel.preso.actualizarpresoResponse1 Carcel.preso.WSPreso.actualizarpreso(Carcel.preso.actualizarpresoRequest request) {
            return base.Channel.actualizarpreso(request);
        }
        
        public bool actualizarpreso(short id, string nombre, ushort sexo, ushort visita, int penal) {
            Carcel.preso.actualizarpresoRequest inValue = new Carcel.preso.actualizarpresoRequest();
            inValue.id = id;
            inValue.nombre = nombre;
            inValue.sexo = sexo;
            inValue.visita = visita;
            inValue.penal = penal;
            Carcel.preso.actualizarpresoResponse1 retVal = ((Carcel.preso.WSPreso)(this)).actualizarpreso(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carcel.preso.actualizarpresoResponse1> Carcel.preso.WSPreso.actualizarpresoAsync(Carcel.preso.actualizarpresoRequest request) {
            return base.Channel.actualizarpresoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carcel.preso.actualizarpresoResponse1> actualizarpresoAsync(short id, string nombre, ushort sexo, ushort visita, int penal) {
            Carcel.preso.actualizarpresoRequest inValue = new Carcel.preso.actualizarpresoRequest();
            inValue.id = id;
            inValue.nombre = nombre;
            inValue.sexo = sexo;
            inValue.visita = visita;
            inValue.penal = penal;
            return ((Carcel.preso.WSPreso)(this)).actualizarpresoAsync(inValue);
        }
    }
}
